
export const SELECT_DELIVERY_ADDRESS_REQUEST = "SELECT_DELIVERY_ADDRESS_REQUEST";
export const SELECT_DELIVERY_ADDRESS_SUCCESS = "SELECT_DELIVERY_ADDRESS_SUCCESS";
export const SELECT_DELIVERY_ADDRESS_FAILURE = "SELECT_DELIVERY_ADDRESS_FAILURE";



