export const CREATE_PAYMENT_LINK_ID_REQUEST = "CREATE_PAYMENT_LINK_ID_REQUEST";
export const CREATE_PAYMENT_LINK_ID_SUCCESS = "CREATE_PAYMENT_LINK_ID_SUCCESS";
export const CREATE_PAYMENT_LINK_ID_FAILURE = "CREATE_PAYMENT_LINK_ID_FAILURE";

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "UPDATE_PAYMENT_FAILURE";
